from sqlalchemy.ext.asyncio import AsyncSession

from app.application.use_cases.external_link_use_case import ExternalLinkUseCase
from app.adapters.output.orm.repositories.external_link_repository_impl import ExternalLinkRepositoryImpl
from app.domain.services.external_link_service import ExternalLinkService
from app.adapters.output.ports.external_link_port_impl import ExternalLinkPortImpl